# Generated by Django 5.1.1 on 2024-10-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('flag', models.URLField()),
                ('season', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('referee', models.CharField(max_length=100)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_city', models.CharField(max_length=100)),
                ('status_long', models.CharField(max_length=100)),
                ('status_short', models.CharField(max_length=20)),
                ('status_elapsed', models.IntegerField()),
                ('goals_home', models.IntegerField()),
                ('goals_away', models.IntegerField()),
                ('score_halftime_home', models.IntegerField()),
                ('score_halftime_away', models.IntegerField()),
                ('score_fulltime_home', models.IntegerField()),
                ('score_fulltime_away', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footstatsapi.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='footstatsapi.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='footstatsapi.team')),
            ],
        ),
    ]
