# Generated by Django 5.1.1 on 2024-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footstatsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='referee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='score_fulltime_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='score_fulltime_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='score_halftime_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='score_halftime_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status_long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status_short',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='venue_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='venue_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='flag',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
