# Generated by Django 5.1.1 on 2024-10-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footstatsapi', '0002_alter_fixture_date_alter_fixture_referee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='season',
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status_elapsed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
