# Generated by Django 5.1.1 on 2024-10-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footstatsapi', '0003_remove_league_season_fixture_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='goals_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='goals_home',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
